fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '3.2.0'
    vcsrepo:
      repo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo.git'

  symlinks:
    seyren: "#{source_dir}"