name    'petems-seyren'
version '0.0.1'
author 'petems'
license 'MIT'
summary 'Seyren is an alerting dashboard for Graphite.'
description 'Seyren is an alerting dashboard for Graphite.'
project_page 'https://github.com/petems/puppet-rbenv'
dependency 'puppetlabs/vcsrepo', '>= 0.1.2'
